### ISSUE TITLE
Footprint for EVQWGD001?

### ISSUE THREAD

**Issue by geocine** [huhu6608/Si4735_Radio#1]
Hi sorry, I really don't know where to contact you so  just trying out my chances here. A friend of mine saw a sketch of your EVQWGD001 dimensions on Taobao. Do you happen to have create a footprint  for use with PCB design?

**Comment by huhu6608** [comment]
Yes,it's me in Taobao. And i draw the footprint at file("Footprint/A.pcb &~/A.sch").
![image](https://user-images.githubusercontent.com/33958010/97290582-b1efd780-1883-11eb-892f-dab81f27ab0f.png)

But they are untested.

**Comment by geocine** [comment]
Thank you that is helpful enough I can test it out
